/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quanlynhansu.view;

import java.io.IOException;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.time.ZoneId;
//import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Date;
import quanlynhansu.model.Account;
import quanlynhansu.model.KhenThuongVaKiLuat;
import quanlynhansu.model.NhanSu;
import quanlynhansu.model.ReadWriteObject;
import quanlynhansu.table.TableNhanSu;

/**
 *
 * @author hxt
 */
public class NhanSuJ extends javax.swing.JFrame {

    /**
     * Creates new form NhanSuJ
     */
    int dongChon = -1;
//     ng;
    ArrayList<NhanSu> dsNS;
    ArrayList<KhenThuongVaKiLuat> ktkl;

    public NhanSuJ() {
        initComponents();
        
        ktkl = new ArrayList<>();
        ktkl.add(new KhenThuongVaKiLuat("Day gioi", "90% sinh vien gioi", "Thuong 500k"));
        ktkl.add(new KhenThuongVaKiLuat("Khong nghi day", "100% đi day", "Thuong 800k"));
        ktkl.add(new KhenThuongVaKiLuat("Nghi day qua so buoi", "50% khong đi day", "Phat 500k"));
        ktkl.add(new KhenThuongVaKiLuat("Danh sinh vien", "Gay thuong tich cho sinh vien", "Duoi viec"));
        
        try {
            dsNS = (ArrayList<NhanSu>) ReadWriteObject.ReadObject("NhanSu.bin");
        } catch (IOException ex) {
            java.util.logging.Logger.getLogger(NhanSuJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NhanSuJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        updateTable();
        jTable1.setAutoCreateRowSorter(true);
    }

    public void updateTable() {

        jTable1.setModel(new TableNhanSu(dsNS));
        try {
            ReadWriteObject.WriteObject("NhanSu.bin", dsNS);
        } catch (IOException ex) {
            java.util.logging.Logger.getLogger(NhanSuJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jSplitPane2 = new javax.swing.JSplitPane();
        tabSua = new javax.swing.JTabbedPane();
        ThongTin = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        ttId = new javax.swing.JLabel();
        ttTen = new javax.swing.JLabel();
        ttSdt = new javax.swing.JLabel();
        ttTenTK = new javax.swing.JLabel();
        ttMatKhau = new javax.swing.JLabel();
        ttBoPhan = new javax.swing.JLabel();
        ttChucDanh = new javax.swing.JLabel();
        ttChucVu = new javax.swing.JLabel();
        ttLuong = new javax.swing.JLabel();
        ttNgayVaoLam = new javax.swing.JLabel();
        ttDemSoNgay = new javax.swing.JLabel();
        ttSoNgayCong = new javax.swing.JLabel();
        ttDiaChi = new javax.swing.JLabel();
        Sua = new javax.swing.JScrollPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        sID = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        sTen = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        sBoPhan = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        sChucDanh = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        sChucVu = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        sTaiKhoan = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        sMatKhau = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        sNgayVaoLam = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        sSoNgayCong = new javax.swing.JSpinner();
        sBTN = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        jButton3.setText("Xoa");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);

        jButton1.setText("Xem luong");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        jButton4.setText("Quay lai");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);

        jScrollPane1.setViewportView(jPanel1);

        jPanel2.add(jScrollPane1);

        jSplitPane1.setLeftComponent(jPanel2);

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        jSplitPane2.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        tabSua.setToolTipText("Chi tiet");

        jPanel3.setLayout(new java.awt.GridLayout(5, 3, 20, 0));

        ttId.setText("ID:");
        jPanel3.add(ttId);

        ttTen.setText("Ten:");
        jPanel3.add(ttTen);

        ttSdt.setText("SDT:");
        jPanel3.add(ttSdt);

        ttTenTK.setText("Ten tai khoan:");
        jPanel3.add(ttTenTK);

        ttMatKhau.setText("Mat khau:");
        jPanel3.add(ttMatKhau);

        ttBoPhan.setText("Bo phan:");
        jPanel3.add(ttBoPhan);

        ttChucDanh.setText("Chuc danh:");
        jPanel3.add(ttChucDanh);

        ttChucVu.setText("Chuc vu:");
        jPanel3.add(ttChucVu);

        ttLuong.setText("Luong:");
        jPanel3.add(ttLuong);

        ttNgayVaoLam.setText("Ngay vao:");
        jPanel3.add(ttNgayVaoLam);

        ttDemSoNgay.setText("So ngay cong hien:");
        jPanel3.add(ttDemSoNgay);

        ttSoNgayCong.setText("So ngay cong:");
        jPanel3.add(ttSoNgayCong);

        ttDiaChi.setText("Dia chi:");
        jPanel3.add(ttDiaChi);

        ThongTin.setViewportView(jPanel3);

        tabSua.addTab("Chi tiet nhan su", ThongTin);

        jPanel5.setLayout(new java.awt.GridLayout(5, 6));

        jLabel33.setText("Id");
        jPanel5.add(jLabel33);
        jPanel5.add(sID);

        jLabel17.setText("Ten");
        jPanel5.add(jLabel17);
        jPanel5.add(sTen);

        jLabel1.setText("Bo phan");
        jPanel5.add(jLabel1);
        jPanel5.add(sBoPhan);

        jLabel2.setText("Chuc danh");
        jPanel5.add(jLabel2);
        jPanel5.add(sChucDanh);

        jLabel3.setText("Chuc vu");
        jPanel5.add(jLabel3);
        jPanel5.add(sChucVu);

        jLabel4.setText("Tai khoan");
        jPanel5.add(jLabel4);
        jPanel5.add(sTaiKhoan);

        jLabel5.setText("Mat khau");
        jPanel5.add(jLabel5);
        jPanel5.add(sMatKhau);

        jLabel6.setText("Ngay vào lam");
        jPanel5.add(jLabel6);
        jPanel5.add(sNgayVaoLam);

        jLabel7.setText("So ngay cong");
        jPanel5.add(jLabel7);
        jPanel5.add(sSoNgayCong);

        sBTN.setText("Cap nhat");
        sBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sBTNActionPerformed(evt);
            }
        });
        jPanel5.add(sBTN);

        Sua.setViewportView(jPanel5);

        tabSua.addTab("Sua", Sua);

        jSplitPane2.setLeftComponent(tabSua);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable1);

        jSplitPane2.setRightComponent(jScrollPane3);

        jPanel4.add(jSplitPane2);

        jSplitPane1.setRightComponent(jPanel4);

        getContentPane().add(jSplitPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        dongChon = jTable1.getSelectedRow();
        if (dongChon != -1) {
            NhanSu x = dsNS.get(dongChon);
            ttBoPhan.setText("Bo phan: " + x.getBoPhan());
            ttChucDanh.setText("Chuc danh: " + x.getcDanh());
            ttChucVu.setText("Chuc vu: " + x.getcVu());
            ttDiaChi.setText("Dia chi: " + x.getdChi());
            ttId.setText("ID: " + x.getId().toString());
            ttLuong.setText("Luong: " + x.getLuong().toString());
            ttMatKhau.setText("Mat khau: " + x.getAcc().getPassword());
            ttNgayVaoLam.setText(x.getNgayVaoLam() == null ? "Ngay vao lam: Khong co" :"Ngay vao lam: " + x.getNgayVaoLam().toString());
            ttSoNgayCong.setText("So ngay cong: " + x.getSongaycong().toString());
            ttTenTK.setText("Ten tai khoan: " + x.getAcc().getUsername());
            ttTen.setText("Ho ten: " + x.getTen());

            sBoPhan.setText(x.getBoPhan());
            sChucDanh.setText(x.getcDanh());
            sChucVu.setText(x.getcVu());
            sID.setText(x.getId().toString());
            sMatKhau.setText(x.getAcc().getPassword());
            sTaiKhoan.setText(x.getAcc().getUsername());
            sTen.setText(x.getTen());
            sNgayVaoLam.setDate(Date.from(x.getNgayVaoLam().atStartOfDay(ZoneId.systemDefault()).toInstant()));
            sSoNgayCong.setValue(x.getSongaycong());
        } else {

        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void sBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sBTNActionPerformed
        // TODO add your handling code here:
        if (dongChon != -1) {
            NhanSu x = dsNS.get(dongChon);

            x.setBoPhan(sBoPhan.getText());
            x.setcDanh(sChucDanh.getText());
            x.setcVu(sChucVu.getText());
//            sID.getText(x.getId().toString());
            x.setAcc(new Account(sTaiKhoan.getText(), sMatKhau.getText()));
            x.setNgayVaoLam(sNgayVaoLam.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate());
            x.setSongaycong((Integer) sSoNgayCong.getValue());

            updateTable();
//            sTen.getText(x.getTen());
        } else {

        }
    }//GEN-LAST:event_sBTNActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (dongChon != -1) {
            dsNS.remove(dongChon);

            updateTable();
//            sTen.getText(x.getTen());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Luong().setVisible(true);
            }
        });
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NhanSuJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NhanSuJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NhanSuJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NhanSuJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NhanSuJ().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane Sua;
    private javax.swing.JScrollPane ThongTin;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton sBTN;
    private javax.swing.JTextField sBoPhan;
    private javax.swing.JTextField sChucDanh;
    private javax.swing.JTextField sChucVu;
    private javax.swing.JLabel sID;
    private javax.swing.JTextField sMatKhau;
    private com.toedter.calendar.JDateChooser sNgayVaoLam;
    private javax.swing.JSpinner sSoNgayCong;
    private javax.swing.JTextField sTaiKhoan;
    private javax.swing.JLabel sTen;
    private javax.swing.JTabbedPane tabSua;
    private javax.swing.JLabel ttBoPhan;
    private javax.swing.JLabel ttChucDanh;
    private javax.swing.JLabel ttChucVu;
    private javax.swing.JLabel ttDemSoNgay;
    private javax.swing.JLabel ttDiaChi;
    private javax.swing.JLabel ttId;
    private javax.swing.JLabel ttLuong;
    private javax.swing.JLabel ttMatKhau;
    private javax.swing.JLabel ttNgayVaoLam;
    private javax.swing.JLabel ttSdt;
    private javax.swing.JLabel ttSoNgayCong;
    private javax.swing.JLabel ttTen;
    private javax.swing.JLabel ttTenTK;
    // End of variables declaration//GEN-END:variables
}
